language: python
python:
- '3.6'
dist: trusty
sudo: required
env:
  global:
  - TRAVIS=True
install:
- pip install -q -r requirements.txt
script:
- python manage.py makemigrations
- python manage.py migrate
- python -m pytest -n 3 --cov-config .coveragerc --cov=. -v
notifications:
  email:
  - keystQuant@gmail.com
  - ppark9553@gmail.com
  on_success: always
  on_failure: always
