language: python
python:
- '3.6'
dist: trusty
sudo: required
env:
  global:
  - DJANGO_VERSION=1.11
  - TRAVIS=True
  - secure: dZQ442x7wdWCF3T2S9O+Cc65/bNIMNKL8rgAIwB28O+/xqV9roNZQYTw4gZR08u+BqcbHRXdcCd9Lv26oeCscroCkva+E45rVSkZ9lYCXmym86kR8K5tytjhcTD9NBx6zCDGdxvfKTeZkKSYf1IQh5e2THYFLdPQDHhbbFJeURwuyBO46Y0OGTqgn8OzKUQUvXyO9d8kHjX/cYgMhWHRs5GUUlIJutKI3+emG7t4JApdhM/tG2gJSvkPHTGrEzFTWUs4UppjEmCCZUrxKTzMCoiQvPSth4YM+ZxiWwwOtVbi/UAzI4IE/GCmwZmaNvhkON8gNdRVQUNjl0+tBR2JSx09hRhzklKE0ednFiD+UuL65GepIk0z9bYsISqzLj9IocpBkFnUhD4Knv2Oo4dJ9wMn5llkr1TClh1YIdYU4eXwEroVzpyo1j7oNEvMGv8eQr8/SegIvshjH9ZbGIGylHqyjQlh3SMESHU0K9e1zbljZSdFgb9Mm9pzhgUOWz0Ary3qNEiedoQGYy1yFMKbU9SHGrAbB9WXxXzyc7O824GFXbcwQsIeN9Oh0kIX8SKWqZy4LTwX8WRjD8Y7sNUqRGi3GWjwlUVz7FRnnYu7VNLxi7nKGlqcbrFLD7sAsz40/WzBoPU2sevQT2NXEwmkHhyxkx4PfAARZTaDswbXXEQ=
install:
- pip install -q Django==$DJANGO_VERSION
- pip install -q -r requirements.txt
script:
- python manage.py makemigrations
- python manage.py migrate
- python -m pytest -n 3 --cov-config .coveragerc --cov=. -v
notifications:
  email:
  - keystQuant@gmail.com
  - ppark9553@gmail.com
  on_success: always
  on_failure: always
