version: "3"

services:
  nginx:
    build: ./config/nginx
    container_name: mined-nginx
    depends_on:
      - web
    links:
      - web:web
    ports:
      - 3000:3000
    restart: unless-stopped

  web:
    build: .
    container_name: mined-server
    restart: unless-stopped
